// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: earthService.proto

package com.example.grpc.protodefine;

public final class EarthServiceOuterClass {
  private EarthServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022earthService.proto\022\034com.example.grpc.p" +
      "rotodefine\032\016dataType.proto2w\n\014EarthServi" +
      "ce\022g\n\010SayHello\022+.com.example.grpc.protod" +
      "efine.CommonRequest\032,.com.example.grpc.p" +
      "rotodefine.CommonResponse\"\000B \n\034com.examp" +
      "le.grpc.protodefineP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.grpc.protodefine.DataType.getDescriptor(),
        });
    com.example.grpc.protodefine.DataType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
