// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sunService.proto

package com.example.grpc.protodefine;

public final class SunServiceOuterClass {
  private SunServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020sunService.proto\022\034com.example.grpc.pro" +
      "todefine\032\016dataType.proto2u\n\nSunService\022g" +
      "\n\010SayHello\022+.com.example.grpc.protodefin" +
      "e.CommonRequest\032,.com.example.grpc.proto" +
      "define.CommonResponse\"\000B \n\034com.example.g" +
      "rpc.protodefineP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.grpc.protodefine.DataType.getDescriptor(),
        });
    com.example.grpc.protodefine.DataType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
