apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: echo-server
  name: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      run: echo-server
  template:
    metadata:
      labels:
        run: echo-server
    spec:
      containers:
      - name: echo-server
        image: nexus.vbox.local:8082/k8s-lb-server-app:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: echo-server
  name: echo-server
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    run: echo-server
  type: ClusterIP
